# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "nvme" "usb_storage" "sd_mod" "rtsx_pci_sdmmc" ];
  boot.initrd.kernelModules = [ "i915" ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/mapper/luks-48809d94-b2b6-4c33-987d-d43065357dbf";
      fsType = "ext4";
    };

  boot.initrd.luks.devices."luks-48809d94-b2b6-4c33-987d-d43065357dbf".device = "/dev/disk/by-uuid/48809d94-b2b6-4c33-987d-d43065357dbf";
  boot.initrd.luks.devices."luks-48809d94-b2b6-4c33-987d-d43065357dbf".allowDiscards = true;

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/98DB-DB29";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };

  swapDevices = [{
    device = "/var/lib/swapfile";
    size = 2*1024;
  }];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
  nixpkgs.hostName = "sahaja";
  services.udev.extraHwdb = ''
  evdev:input:b0011v0001p0001*
    KEYBOARD_KEY_01=capslock
    KEYBOARD_KEY_3a=esc
    KEYBOARD_KEY_b8=leftctrl
    KEYBOARD_KEY_38=leftctrl
    KEYBOARD_KEY_b7=leftalt
    KEYBOARD_KEY_db=leftalt
    KEYBOARD_KEY_9d=leftmeta
    KEYBOARD_KEY_1d=leftmeta
  '';
}
