# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports = [ 
    (modulesPath + "/installer/scan/not-detected.nix")
    ../modules/etc-issue-wordsworth.nix
    ../modules/kbd-apple-jap.nix
    ];

  nixpkgs.config.permittedInsecurePackages = [ "broadcom-sta-6.30.223.271-59-6.17.9" ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "nvme" "usbhid" "usb_storage" "sd_mod" ];
  boot.initrd.kernelModules = [ "i915" ]; # or else setting console font breaks, use i915 for intel
  boot.kernelModules = [ "kvm-intel" "wl" ];
  boot.extraModulePackages = [ config.boot.kernelPackages.broadcom_sta ];

  fileSystems."/" =
    { device = "/dev/mapper/luks-6d5b0aa3-78d1-4214-811c-bd6c9aeb1475";
      fsType = "ext4";
    };

  boot.initrd.luks.devices."luks-6d5b0aa3-78d1-4214-811c-bd6c9aeb1475".device = "/dev/disk/by-uuid/6d5b0aa3-78d1-4214-811c-bd6c9aeb1475";
  boot.initrd.luks.devices."luks-6d5b0aa3-78d1-4214-811c-bd6c9aeb1475".allowDiscards = true;

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/BB34-3479";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };

  swapDevices = [{
    device = "/var/lib/swapfile";
    size = 4*1024; # 16 GB
  }];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
  networking.hostName = "genesis"; # Define your hostname.
}
