# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  nixpkgs.config.permittedInsecurePackages = [ "broadcom-sta-6.30.223.271-59-6.17.9" ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "nvme" "usbhid" "usb_storage" "sd_mod" ];
  boot.initrd.kernelModules = [ "i915" ]; # or else setting console font breaks, use i915 for intel
  boot.kernelModules = [ "kvm-intel" "wl" ];
  boot.extraModulePackages = [ config.boot.kernelPackages.broadcom_sta ];

  fileSystems."/" =
    { device = "/dev/mapper/luks-6d5b0aa3-78d1-4214-811c-bd6c9aeb1475";
      fsType = "ext4";
    };

  boot.initrd.luks.devices."luks-6d5b0aa3-78d1-4214-811c-bd6c9aeb1475".device = "/dev/disk/by-uuid/6d5b0aa3-78d1-4214-811c-bd6c9aeb1475";
  boot.initrd.luks.devices."luks-6d5b0aa3-78d1-4214-811c-bd6c9aeb1475".allowDiscards = true;

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/BB34-3479";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };

  swapDevices = [{
    device = "/var/lib/swapfile";
    size = 4*1024; # 16 GB
  }];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
  networking.hostName = "genesis"; # Define your hostname.
  # This was a mad layout to figure out! It's a Japanese Layout MBA
  # https://bbs.archlinux.org/viewtopic.php?id=260804
  services.udev.extraHwdb = ''
  evdev:input:b0003v05ACp0290*
    KEYBOARD_KEY_70029=capslock
    KEYBOARD_KEY_70039=fn
    KEYBOARD_KEY_70090=leftctrl
    KEYBOARD_KEY_70091=leftctrl
    KEYBOARD_KEY_700e7=leftalt
    KEYBOARD_KEY_700e3=leftalt
    KEYBOARD_KEY_700e2=leftmeta
    KEYBOARD_KEY_700e0=esc
    KEYBOARD_KEY_70089=backspace
    KEYBOARD_KEY_70087=grave
    KEYBOARD_KEY_ff0003=rightmeta
  '';
}
