# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "nvme" "usb_storage" "sd_mod" ];
  boot.initrd.kernelModules = [ "i915" ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/918fe89d-2e81-4710-aaea-0f5c43d67a26";
      fsType = "ext4";
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/0820-1D5D";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };

  fileSystems."/home" =
    { device = "/dev/mapper/luks-c5748b76-2409-4b74-a094-76d4b5bc7045";
      fsType = "ext4";
    };

  boot.initrd.luks.devices."luks-c5748b76-2409-4b74-a094-76d4b5bc7045".device = "/dev/disk/by-uuid/c5748b76-2409-4b74-a094-76d4b5bc7045";
  boot.initrd.luks.devices."luks-c5748b76-2409-4b74-a094-76d4b5bc7045".allowDiscards = true;

  swapDevices = [ { device = "/dev/disk/by-uuid/7f7997a6-05f3-4a54-acbe-4658a4ba0f82"; } ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;

  networking.hostName = "cardiel";
  services.udev.extraHwdb = ''
  evdev:input:b0011v0001p0001*
    KEYBOARD_KEY_01=capslock
    KEYBOARD_KEY_3a=esc
    KEYBOARD_KEY_b8=leftctrl
    KEYBOARD_KEY_38=leftctrl
    KEYBOARD_KEY_b7=leftalt
    KEYBOARD_KEY_db=leftalt
    KEYBOARD_KEY_9d=leftmeta
    KEYBOARD_KEY_1d=leftmeta
  '';
}
